//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComentariosNoticias
    {
        public int id { get; set; }
        public Nullable<int> idNoticia { get; set; }
        public string idUsuario { get; set; }
        public string comentario { get; set; }
        public Nullable<System.DateTime> fechaComentario { get; set; }
    
        public virtual Noticias Noticias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
