//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntranetEntities : DbContext
    {
        public IntranetEntities()
            : base("name=IntranetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComentariosNoticias> ComentariosNoticias { get; set; }
        public virtual DbSet<Correspondencia> Correspondencia { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Gerencias> Gerencias { get; set; }
        public virtual DbSet<Hijos> Hijos { get; set; }
        public virtual DbSet<Noticias> Noticias { get; set; }
        public virtual DbSet<Paginas> Paginas { get; set; }
        public virtual DbSet<Subgerencias> Subgerencias { get; set; }
        public virtual DbSet<TiposContrato> TiposContrato { get; set; }
        public virtual DbSet<Ubicaciones> Ubicaciones { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
