//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.ComentariosNoticias = new HashSet<ComentariosNoticias>();
            this.Hijos = new HashSet<Hijos>();
        }
    
        public string rutUsuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string cargo { get; set; }
        public string gerencia { get; set; }
        public string subgerencia { get; set; }
        public string departamento { get; set; }
        public string ubicacion { get; set; }
        public string jefe { get; set; }
        public string rolUsuario { get; set; }
        public string tipoContrato { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public string email { get; set; }
        public Nullable<int> celular { get; set; }
        public Nullable<int> hijo { get; set; }
        public string nombreHijo { get; set; }
        public string contraseña { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentariosNoticias> ComentariosNoticias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hijos> Hijos { get; set; }
    }
}
